### PR TITLE
add description on stream setup to URL for DSLR

### PR DESCRIPTION
**Pull request by DominicWindisch**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)
- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)
Add description on how to install and setup live stream for DSLR as it is allready supported but not documented.

#### Is there anything you'd like reviewers to focus on?
nope

### CODE REVIEW

**Comment by andi34** [comment]
As capture command `capture %` will be needed for the capturing to work, this also need to be mentioned.

**Comment by andi34** [comment]
`select the `--mjpeg` version when running the install script.` --> maybe better something like _add the --mjpeq flag while running the install script._ ?

**Comment by DominicWindisch** [comment]
TBH, I've switched to using photobooth-app (which appears to be working better for my camera) so I can't check the correct command at the moment. I just wanted to document our discussion on the issue for other users in a more finable way.

Please add the appropriate command to the docs yourself.

_add the --mjpeg flag when running the install script_ sounds fine to me.

**Comment by andi34** [comment]
@dadav maybe we can also make it installable afterwards without running the whole installer?

**Pull request merged**
