### PR TITLE
task: drop usage of scss variables and embrace css properties

### PR DESCRIPTION
**Pull request by benjaminkott**
#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Other, please explain:

#### What changes did you make? (Give an overview)

Since the SCSS variables are already filled with CSS properties 
there is no need anymore to keep them around. The build result 
does not change and has no impact on users at all.

### CODE REVIEW

**Comment by benjaminkott** [comment]
Note: 
- font awesome paths are still kept as they are necessary for the third-party lib
- error, success, and checked colors are still kept since they have no general settings yet

**Comment by andi34** [comment]
Hey and good morning!
Thanks for the suggestion, but I've started to rework the UI using tailwindcss already:
https://github.com/PhotoboothProject/photobooth/tree/feature/tw-ui

There's some work left to do, but it's enough to get an idea about what's changing (branch will be force pushed frequently until it's ready for review).

**Comment by benjaminkott** [comment]
Good Morning, I saw your tailwind changes - I have to confess, that I am not a big tailwind fan.  
It´s not about tailwind in specific, it´s more like Utility-CSS frameworks in general. 

But I have to admit, It always depends on the use case. 
While Utility CSS-Frameworks are great for rapid prototyping, 
they are the worst-case for maintaining customizable, themeable, environments. 

You can already see the negative impact in your `tw-ui` branch.

```
<!-- Buttons -->
<div class="loading rotarygroup">
    <a class="<?= $btnClass ?> rotaryfocus ml-2 hidden" href="#" id="btnCollageNext"><span data-i18n="nextPhoto"></span></a>
    <a class="<?= $btnClass ?> rotaryfocus ml-2 hidden" href="#" id="btnCollageProcess""><span data-i18n="processPhoto"></span></a>
    <a class="<?= $btnClass ?> rotaryfocus ml-2 hidden" href="#" id="btnCollageRetake"><span data-i18n="retakePhoto"></span></a>
    <a class="<?= $btnClass ?> rotaryfocus ml-2 hidden" href="#" id="btnCollageAbort""><span data-i18n="abort"></span>    </a>
</div>
```

```
// Button Configs

// modern
$btnClasses['modern'] = ' inline-flex m-2 items-center justify-center flex-col shrink-0 grow-0';
$shapeClasses['modern'] = 'rounded-md';
$btnShapeClasses['modern'] = 'rounded-full';
$borderClasses['modern'] = 'border-solid border-4 border-btn-border';
$btnSize['modern'] = 'w-16 h-16 md:w-24 md:h-24 lg:w-28 lg:h-28';
```

This is only the beginning of this and will need to extend to all kinds of areas.
My point here is, that this should not be necessary in the first place.

I would like to propose a different route here:

1. Unify the markup rendered
1. Avoid template overrides whenever possible
1. Introduce preconditioned components
1. Make adjustments via CSS only


Example:

```
<!-- base css -->
:root {
  --button-border-radius: 0;
}
.button {
  border-radius: var(--border-radius);
}
```

```
<!-- modern.css -->
:root {
  --button-border-radius: .25rem;
}
```

```
<!-- modern-round.css -->
:root {
  --button-border-radius: 50%;
}
```

This will require some rework and will be breaking for users' customizations.
Users would benefit in the long term from more easy and reliable customizations.

Can share more insights into maintaining such systems if you like.
Just ping me, and we can hop into a call.

**Comment by benjaminkott** [comment]
Back to the original PR, I am currently facing some CSS bugs on my Android tablet. I started investigating and am currently trying to understand the underlying structure and how themes make use of the available CSS. This is just an initial cleanup patch to better see what is used where.

**Pull request merged**
