### PR TITLE
Feature/small improvements

### PR DESCRIPTION
**Pull request by up-87**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [X] Other, please explain:
minor improvements

#### What changes did you make? (Give an overview)
- getting camera preview ready before displaying it in collages (removes short black flicker)
- countdown style changes (I really disliked the small number that stayed so I continued the animation for the whole second and started with a bit bigger number, I hope this is not too much my personal taste)

### CODE REVIEW

**Comment by andi34** [comment]
Looks good to me. Preview works from device Cam, Countdown looks a lot smoother now! Thanks a lot!

I noticed, while taking a new Image or Collage from result Screen, the Home Button is still visible. This should be solved in this PR too.

Do you have time to look at it?

**Comment by up-87** [comment]
Will look at that and fix that tomorrow.

**Comment by andi34** [comment]
The `position: fixed` CSS for homebtn seems to be the problem. Unsure how to rework that to keep the position. We could hide it by default and make it visible from core.js maybe?
Or add a new div which is visible on top and can disappears on top (Like the `resultInner`?)

**Comment by andi34** [comment]
Homebtn shoud be fixed now.
I'll also Take a look at the Gallery Button too in the evening.

**Review by andi34 — APPROVED** [review]
Thanks a lot again =)

**Pull request merged**
