### PR TITLE
Restructure preview handling, add testpage for preview settings

### PR DESCRIPTION
**Pull request by andi34**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [x] Other, please explain: restructure preview code

#### What changes did you make? (Give an overview)

Seperate preview functions to it's own javascript to be used where needed.
Also add a simple test page to test defined preview settings.

### CODE REVIEW

**Comment by andi34** [comment]
Todo:
- add needed translations 
- add functionality to stop Preview button
- add start preview Button which is visible if preview was stopped
- show info if no preview available/not ready

To think about:
Refresh button?

**Comment by andi34** [comment]
I am not sure if using a own .js file is a good solution, more code to maintain. Maybe there's a way to move the core preview functionality to a own js file in general and use the preview functions where needed? Same as we do for the Photobooth tools.js.

**Comment by up-87** [comment]
Yes, I'd say that'd be the way to go. The core.js file is too big anyway. We should split it up into meaningful parts and reuse that for the preview. If we don't use the same code we might make it that the preview test works but the actual preview fails which would be really confusing for the user.

**Comment by andi34** [comment]
Thanks for your comment.
I'll take a look at the Todo parts to make the test functional first. After that we should take a look at the restructuring.

**Comment by andi34** [comment]
@up-87 like this? Or you've got a cleaner idea?

**Comment by up-87** [comment]
I dislike that the selectors are passed to that many functions. I'd initialize the photoboothPreview with these selectors as it doesn't have a lot of reason to exist without them. Wherever the api needs the selectors it could obtain them from the photoboothPreview. Then there's no need to have them as param in so many methods.

**Comment by andi34** [comment]
Thanks for your review!
Do you like to push another commit with those changes?

**Comment by up-87** [comment]
ok

**Pull request merged**
