### PR TITLE
Restructure: add initial helper classes

### PR DESCRIPTION
**Pull request by andi34**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Other, please explain: restructure

### CODE REVIEW

**Comment by andi34** [comment]
Hey Uwe!
What do you think about that?
I'd also like to put all the effects (text on, frame, rotation etc) into classes to use. IMO this way we could make the post processing easy to adjust (e.g. by allowing user to override functions and only process without if checks what's needed and left out what doesn't need to be executed/checked.

Your opinion on that?

**Comment by up-87** [comment]
Only scanned over it for now... Definitely makes sense! The program flow shouldn't read too much from the config itself. In most cases this can be done in classes and then it's quite easy to reuse code (like with the collage config for my video collages)

**Comment by andi34** [comment]
Windows compatibly need to be fixed. Need to test further.

**Comment by andi34** [comment]
Hey Uwe! Anything against merging it?

**Pull request merged**
