### PR TITLE
rework(preview): remove gphoto preview option

### PR DESCRIPTION
**Pull request by andi34**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [X] Other, please explain: preview "from gphoto" might be missleading

#### What changes did you make? (Give an overview)
Preview "from gphoto2" was always the same as preview "from device cam", with the difference a command gets executed to start the preview before it can be used.
If preview is set to "from device cam", the start preview command is executed if defined. Time to execute the start preview command depends on the BSM config (_"Execute start command for preview on take picture/collage"_).
The stop preview command now only gets executed if defined.

Old information about the preview from gphoto2 have been removed from the FAQ and other parts have been updated.

### CODE REVIEW

**Comment by andi34** [comment]
I'll update later or tomorrow. Review can wait until that @up-87

**Comment by andi34** [comment]
~Language resources and FAQ need to be adjusted again. Will do later.~

**Comment by andi34** [comment]
@up-87 Ready to be tested with a DSLR, I am unable to test myself as my DSLR doesn't support live preview. I'll only squash the faq and language changes into the _remove preview "from device cam with start- and stop command"_ commit in the evening and force push.

**Comment by up-87** [comment]
Works fine with gphoto. I tested with my python script but that shouldn't make a difference. I tested it with and without bsm.

**Comment by andi34** [comment]
Great! Thanks a lot! Do you see anything to be improved?
Btw I removed the old instructions and only mentioned the `cameracontrol.py` in the FAQ.

**Comment by up-87** [comment]
I quickly checked the code changes and they seem pretty straight-forward.
cameracontrol.py seems to be stable enough that we can recommend it as a default. It was recommended for all users having problems and I don't recall any script specific issues.

**Comment by andi34** [comment]
Fix https://github.com/PhotoboothProject/photobooth/issues/30

**Pull request merged**
