### PR TITLE
Feature/gif

### PR DESCRIPTION
**Pull request by up-87**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [X] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)
Added video as third mode next to picture and collage. The mode works hand in hand with cameracontrol.py. It can record a short video and create a collage from that video. The collage has the predefined collage style 4x2 and it consists of frames that are saved while the video is created. If a collage is created while recording a video that collage can be printed from the review where the video is shown. For the video there's a qr code to download the video but currently that's the only thing that can be done with the video itself as the gallery can't display it at the moment.

#### Is there anything you'd like reviewers to focus on?
Quite a of changes. Collage style definition was moved to a class to enable a predefined second style. Basically all other changes only work with cameracontrol.py or in theory another command that records a video (and images) with the expected names.

### CODE REVIEW

**Comment by up-87** [comment]
Sending the video by mail might work. Didn't think about it or test it.

**Comment by up-87** [comment]
Additionally I noticed that the ffmpeg command started by cameracontrol.py fails sometimes. I'll have to look into that and see how I can handle or prevent that issue.

**Comment by andi34** [comment]
Wow, 80 commits!
IMO it make sense to seperate the collage code changes and other improvements independent of the video feature and merge them first.

As I've no camera with live Preview, I am unable to test this feature, right?

**Comment by up-87** [comment]
I‘d say about 30 commits would be more reasonable 🙈. Commiting and pulling is the most convenient way to get code to my photobooth from my development environment when I was working on multiple files.

Yes, I‘ll try to separate simple code improvements that make sense for future development in a new branch. I‘ll make new commits for this new feature, as well.

and yes, the new features only work if you‘re able to get a live preview through cameracontrol as it records videos and images from this preview.

**Comment by andi34** [comment]
Don't worry, I am also cleaning up commits mist of the time at a later point, especially if I am commiting mobile.
I am used to work with different Patchsets for a commit until it's fine from Android development (e.g. like ok this https://review.lineageos.org/c/LineageOS/android_frameworks_native/+/286683), I know not everyone likes. But in case something breaks it's easier to find the devil.

Maybe we can look at it later to get it work with raspivid / libcamera-vid too?

**Comment by up-87** [comment]
In the end the new php file that applies the video effects just needs a video file that ffmpeg can read and / or a set of image files. (At the beginning all video handling was done through cameracontrol. then I fortunately made the decision that it‘s a lot more reasonable to do postprocessing like with images. Feedback for the user is a lot better this way, as well)

**Comment by andi34** [comment]
Ok, libcamera-vid should be able to produce a video file which can be used. Guess there's a Python thing too which can be used similar to the libgphoto.

**Comment by andi34** [comment]
https://github.com/raspberrypi/picamera2

**Comment by up-87** [comment]
replaced by two pull requests:
one for the improvements and one for the video feature

**Pull request closed without merging**
