### PR TITLE
Update selfie feature

### PR DESCRIPTION
**Pull request by huebim**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

_New Button "Take a Picture" Style
Preview Picture 
Warn Message MaxFileSize only less 5MB_

#### Is there anything you'd like reviewers to focus on?

_Next TODO: 
Warn Message if image bigger then MaxFileSize
"selfie" integration in admin config
button in gallery to "selfie" if it is allowed in the admin panel
gallery portrait format padding left and right 20%
gallery and slideshow on localhost running system have to refresh on db changes_

### CODE REVIEW

**Comment by andi34** [comment]
https://github.com/PhotoboothProject/photobooth/blob/dev/gallery/index.php#L30

Standalone gallery has the feature already to check for DB changes and reload if is.

**Comment by andi34** [comment]
Standalone slideshow checks always like defined for gallery and reloads if needed

https://github.com/PhotoboothProject/photobooth/blob/dev/assets/js/slideshow.js#L184

**Comment by huebim** [comment]
New Design in Selfie index.php (upload button only visible when picture in memory and filesize in php posible), removed slidshow button (there is no way to go back)
add selfie button on gallery index.php and hidden on overlay mode, (perfekt QR-Link for all guests)
remove reload button on overlay gallery
TODO:
admin panel ON/OFF Selfie Feature
overlay Gallery refresh db

**Comment by huebim** [comment]
I NEED HELP.
I want to integrate the selfie feature into the admin panel with a checkbox on/off and the result should be available in the $config[selfie][enabled] to be used in php. I hope someone can help me with the integration, I'm just destroying the project trying.

**Pull request closed without merging**
