### PR TITLE
Donations: charity time!

### PR DESCRIPTION
**Pull request by andi34**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/PhotoboothProject/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Other, please explain: no money donations - charity time!

### CODE REVIEW

**Comment by andi34** [comment]
Text ok? Something can be spelled better?

**Comment by mgineer85** [comment]
Maybe lower the barrier and provide deep links like https://www.dkms.de/aktiv-werden/geld-spenden Preferably in Englisch language if available? 
Do you have an overview in which counties most people live using PhotoBooth? You could add some local organizations similar to dkms…?

**Review by ledsi — APPROVED** [review]
Text is nice, love the decision to give the donations to organizations that will care about cancer!

**Comment by andi34** [comment]
@mgrl https://webforms.dkms.de/en/DE/moneydonation/paypal maybe? Most user are from Germany I think, some from France, some from Italy. There's no other organization I know and would keep it.

**Pull request merged**
